#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.2 on Tue Mar 14 17:57:05 2017
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.choice_radio_box = wx.RadioBox(self, wx.ID_ANY, _("Choose Selection:"), choices=[_("Geotag"), _("Address")], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _("Enter search terms in this format:\nGeoTag : latitude, longitutde\nAddress: 123 Some Rd, City, State"), style=wx.ALIGN_CENTER_HORIZONTAL)
        self.search_box = wx.TextCtrl(self, wx.ID_ANY, "")
        self.search_btn = wx.Button(self, wx.ID_ANY, _("Search"), style=wx.BU_EXACTFIT)
        self.r_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle(_("xPyGeolocate"))
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("/root/scripts/python/gtk/icons/pygeolocate.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((295, 241))
        self.choice_radio_box.SetSelection(0)
        self.search_box.SetMinSize((225, 25))
        self.search_btn.SetMinSize((65, 25))
        self.r_text_ctrl.SetMinSize((275, 75))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.choice_radio_box, 0, wx.ALL | wx.EXPAND, 0)
        sizer_1.Add(self.label_1, 0, wx.ALIGN_CENTER, 0)
        sizer_2.Add(self.search_box, 0, wx.ALIGN_BOTTOM, 0)
        sizer_2.Add(self.search_btn, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT, 0)
        sizer_1.Add(sizer_2, 1, 0, 0)
        sizer_1.Add(self.r_text_ctrl, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

        #set bindings
        #self.choice_radio_box.Bind(wx.EVT_RADIOBOX,self.onRadioBox)
        self.search_btn.Bind(wx.EVT_BUTTON, self.onButton)

    def onButton(self, event):
        self.search_box.SetLabel(self.r_text_ctrl.GetValue())        
        

# end of class MainFrame
if __name__ == "__main__":
    gettext.install("PyGeoLocate") # replace with the appropriate catalog name

    PyGeoLocate = wx.PySimpleApp()
    main_frame = MainFrame(None, wx.ID_ANY, "")
    PyGeoLocate.SetTopWindow(main_frame)
    main_frame.Show()
    PyGeoLocate.MainLoop()
